# Generated by Django 3.2 on 2023-10-31 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20230923_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='substitute_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='代役ユーザー', to=settings.AUTH_USER_MODEL),
        ),
    ]
