# Generated by Django 3.2 on 2023-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shift_substitute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_myself',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
