# Generated by Django 3.2 on 2023-12-15 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231118_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('position', models.CharField(default='all', max_length=10)),
            ],
        ),
    ]
