# Generated by Django 3.2 on 2023-12-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_registeredshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='休憩開始')),
                ('end_time', models.TimeField(verbose_name='休憩終了')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registeredshift')),
            ],
        ),
    ]
