# Generated by Django 3.2 on 2023-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='view_type',
            field=models.CharField(default='red', max_length=5),
        ),
    ]
