# Generated by Django 3.2 on 2023-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='chick', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='view_type',
            field=models.CharField(default='mix', max_length=5),
        ),
    ]
