# Generated by Django 3.2 on 2023-11-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_view_type'),
        ('auth_app', '0003_auto_20231102_0344'),
    ]

    operations = [
    ]
