# Generated by Django 3.2 on 2023-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_auto_20231117_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='store_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
